module.exports = {
	buildings: {
		"1":	{ street: "Лесная",   "house":	1 },
		"2":	{ street: "Лесная",   "house":	3 },
		"3":	{ street: "Лесная",   "house":	5 },
		"4":	{ street: "Лесная",   "house":	7 },
		"5":	{ street: "Лесная",   "house":	9 },
		"6":	{ street: "Лесная",   "house":	11 },
		"7":	{ street: "Лесная",   "house":	13 },
		"8":	{ street: "Лесная",   "house":	15 },
		"9":	{ street: "Лесная",   "house":	17 },
		"10":	{ street: "Лесная",   "house":	10 },
		"11":	{ street: "Лесная",   "house":	21 },
		"12":	{ street: "Лесная",   "house":	23 },
		"13":	{ street: "Лесная",   "house":	25 },
		"14":	{ street: "Лесная",   "house":	27 },
		"15":	{ street: "Лесная",   "house":	42 },
		"16":	{ street: "Лесная",   "house":	40 },
		"17":	{ street: "Лесная",   "house":	38 },
		"18":	{ street: "Лесная",   "house":	36 },
		"19":	{ street: "Лесная",   "house":	34 },
		"22":	{ street: "Лесная",   "house":	32 },
		"23":	{ street: "Лесная",   "house":	30 },
		"25":	{ street: "Лесная",   "house":	28 },
		"26":	{ street: "Лесная",   "house":	6 },
		"27":	{ street: "Лесная",   "house":	26 },
		"28":	{ street: "Лесная",   "house":	24 },
		"29":	{ street: "Лесная",   "house":	22 },
		"30":	{ street: "Лесная",   "house":	20 },
		"31":	{ street: "Лесная",   "house":	18 },
		"32":	{ street: "Лесная",   "house":	16 },
		"33":	{ street: "Лесная",   "house":	14 },
		"34":	{ street: "Лесная",   "house":	12 },
		"35":	{ street: "Лесная",   "house":	10 },
		"37":	{ street: "Лесная",   "house":	8 },
		"39":	{ street: "Лесная",   "house":	6 },
		"40":	{ street: "Лесная",   "house":	4 },
		"41":	{ street: "Лесная",   "house":	2 },
		"42":	{ street: "Звездная", "house":	5 },
		"43":	{ street: "Звездная", "house":	3 },
		"44":	{ street: "Звездная", "house":	1 },
		"45":	{ street: "Звездная", "house":	29 },
		"46":	{ street: "Звездная", "house":	27 },
		"47":	{ street: "Звездная", "house":	25 },
		"48":	{ street: "Звездная", "house":	20 },
		"49":	{ street: "Звездная", "house":	22 },
		"50":	{ street: "Звездная", "house":	24 },
		"51":	{ street: "Звездная", "house":	26 },
		"52":	{ street: "Звездная", "house":	2 },
		"53":	{ street: "Звездная", "house":	4 },
		"54":	{ street: "Звездная", "house":	7 },
		"55":	{ street: "Звездная", "house":	9 },
		"56":	{ street: "Звездная", "house":	11 },
		"57":	{ street: "Звездная", "house":	13 },
		"58":	{ street: "Звездная", "house":	15 },
		"59":	{ street: "Звездная", "house":	17 },
		"60":	{ street: "Звездная", "house":	19 },
		"61":	{ street: "Южная", 	  "house":	3 },
		"62":	{ street: "Южная", 	  "house":	5 },
		"63":	{ street: "Южная", 	  "house":	7 },
		"64":	{ street: "Южная", 	  "house":	11 },
		"65":	{ street: "Южная", 	  "house":	13 },
		"66":	{ street: "Южная", 	  "house":	15 },
		"67":	{ street: "Южная", 	  "house":	2 },
		"68":	{ street: "Южная", 	  "house":	4 },
		"69":	{ street: "Южная", 	  "house":	6 },
		"69а":	{ street: "Южная", 	  "house":	8 },
		"70":	{ street: "Южная", 	  "house":	10 },
		"71":	{ street: "Южная", 	  "house":	12 },
		"72":	{ street: "Южная", 	  "house":	14 },
		"73":	{ street: "Южная", 	  "house":	16 },
		"74":	{ street: "Южная", 	  "house":	18 },
		"74а":	{ street: "Южная", 	  "house":	20 },
		"75":	{ street: "Южная", 	  "house":	22 },
		"76":	{ street: "Южная", 	  "house":	24 },
		"77":	{ street: "Южная", 	  "house":	26 },
		"78":	{ street: "Южная", 	  "house":	28 },
		"79":	{ street: "Звездная", "house":	21 },
		"80":	{ street: "Звездная", "house":	23 },
		"81":	{ street: "Звездная", "house":	14 },
		"82":	{ street: "Северный тупик", "house":	7 },
		"83":	{ street: "Звездная", "house":	18 },
		"84":	{ street: "Северный тупик", "house":	10 },
		"85":	{ street: "Северный тупик", "house":	8 },
		"86":	{ street: "Северный тупик", "house":	6 },
		"87":	{ street: "Северный тупик", "house":	4 },
		"88":	{ street: "Северный тупик", "house":	2 },
		"89":	{ street: "Звездная", "house":	6 },
		"90":	{ street: "Звездная", "house":	8 },
		"91":	{ street: "Звездная", "house":	10 },
		"92":	{ street: "Звездная", "house":	12 },
		"93":	{ street: "Северный тупик", "house":	5 },
		"94":	{ street: "Северный тупик", "house":	3 },
		"95":	{ street: "Северный тупик", "house":	1 },
		"96":   { street: "Звездная", "house":  31 }
	}
};